<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>a27d4449-20b9-4867-b706-03963c085adb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#closeSmallModal-ok</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='closeSmallModal-ok']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4e204f7b-a2fc-44c1-97a4-0a8c77a3b76a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>closeSmallModal-ok</value>
      <webElementGuid>5fbced8e-e63a-484c-937c-b3908773cd85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>271b98c6-82cb-4f3e-9705-1f644d650c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>ed224ec1-ac7f-4553-b731-0fb46f11e0c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>6047e628-ef92-4aab-8cad-1f9602f244c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;closeSmallModal-ok&quot;)</value>
      <webElementGuid>155605a3-6bf8-430c-b4b9-6b2eec42be1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='closeSmallModal-ok']</value>
      <webElementGuid>e6324a6e-cabc-41fa-808f-ee2000b207a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[3]/button</value>
      <webElementGuid>ebd45395-eb33-428e-be9e-2f14e3007d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'closeSmallModal-ok' and @type = 'button' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>c8ccf9d7-0bc1-4454-b4d9-738e1df261a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
