<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_a-q25y7o9w2783</name>
   <tag></tag>
   <elementGuidId>2280e9a7-3e2a-4dc0-87cf-f74bfcdf619b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-q25y7o9w2783&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-q25y7o9w2783']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>231f6cd8-77fb-482a-a6dd-df379d44adf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>7c4fbc24-af69-4fbb-9ec5-ad636e41b600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>2b5e7831-845e-44bc-9f4a-df353457b32c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>b6f98d0d-aa7a-4102-bca1-7fe49c297d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>1345f2da-d7eb-49c0-b79f-df18bdf2d5b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-q25y7o9w2783</value>
      <webElementGuid>eb83e80b-34cf-4370-854c-9acdef750fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8fbfffbf-b3a4-448a-88fd-3e16c087ba48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>7da0f4ca-f6c2-4dd5-8ccb-84fc76be925e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>112d2233-7c65-46ba-ace3-6081931a5f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7&amp;co=aHR0cHM6Ly9kZW1vcWEuY29tOjQ0Mw..&amp;hl=en&amp;type=image&amp;v=QUpyTKFkX5CIV6EF8TFSWEif&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=me8xrqb96oss</value>
      <webElementGuid>ccf5eaa4-4778-4ca4-ba19-a4739d47bf50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g-recaptcha&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>127b7021-170f-49e0-88b8-986d9dccc9d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-q25y7o9w2783']</value>
      <webElementGuid>382adc04-41ed-4a35-8a34-db5683eb547a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g-recaptcha']/div/div/iframe</value>
      <webElementGuid>0092f5bd-8342-4617-846d-aea616a191fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/iframe</value>
      <webElementGuid>0f94ec8d-f5b0-488f-ab09-a3c5a64a848c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-q25y7o9w2783' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7&amp;co=aHR0cHM6Ly9kZW1vcWEuY29tOjQ0Mw..&amp;hl=en&amp;type=image&amp;v=QUpyTKFkX5CIV6EF8TFSWEif&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=me8xrqb96oss']</value>
      <webElementGuid>4acf484d-6624-4800-9f21-799dbc31c519</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
